name: Bug Report
description: Report a bug in RustChain node, miner, or wallet
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Report a Bug
        Thanks for helping improve RustChain! Bug fixes can earn RTC bounties.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Node (rustchain_v2_integrated)
        - Miner (rustchain_*_miner)
        - Wallet (rustchain_wallet_*)
        - Consensus (RIP-200)
        - API Endpoint
        - Block Explorer
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
      placeholder: When I run the miner with --wallet flag, it crashes with...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `python3 rustchain_linux_miner.py --wallet test`
        2. Wait for attestation cycle
        3. See error in log
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: Which version or commit hash?
      placeholder: v2.2.1-rip200 or commit abc1234

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (x86_64)
        - Linux (ARM/aarch64)
        - Linux (PowerPC)
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error messages or logs
      render: shell
